version: '3'
services:

  postgres:
    image: postgres:16-alpine
#    shm_size:
    restart: always
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=${PSQL_SHARED_BUFFERS}"
      - "-c"
      - "temp_buffers=32MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "wal_buffers=32MB"
      - "-c"
      - "max_wal_size=${PSQL_MAX_WAL_SIZE}"
      - "-c"
      - "min_wal_size=80MB"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "idle_in_transaction_session_timeout=5min"
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: dev_auth_user
      POSTGRES_PASSWORD:
      POSTGRES_DB: job_aggr_auth
    ports:
      - 127.0.0.1:5435:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

#  redis:
#    image: redis:7-alpine
#    restart: always
#    volumes:
#      - redis_data:/data
#    logging:
#      driver: none

  authentication:
    build:
      context: ./authentication
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - postgres
      - redis
    env_file: &env_file
      - ./.env
    entrypoint: /home/user/app/entrypoint.sh
    ports:
      - 127.0.0.1:8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./static:/home/user/static"
      - "./tmp:/home/user/tmp"



#  authorization:
#    build: ./authorization
#    environment:
#      - DB_NAME=