TG_MESSAGE_WIDTH = 32


ICON_DONE = "✅"
ICON_DENY = "❌"
ICON_STOP = "⛔"
ICON_WARNING = "⚠️"
ICON_BACK = "⬅️"
ICON_WAIT = "⏳"

ICON_OZON_DISCOUNT = "🙂"
ICON_OZON_NODISCOUNT = "😡"
ICON_RATING = "⭐"
ICON_STOCK = "📦"
ICON_USERS = "👥"
ICON_CART = "🛒"
ICON_ORDER = "🚚"
ICON_REVENUE = "💰"
ICON_MONEY = "💵"
ICON_RETURNS = "😡"
ICON_ADVERT = "📣"
ICON_LOOKUP = "☝️"

ICON_GREEN = "🟢"
ICON_YELLOW = "🟡"
ICON_RED = "🔴"

TASK_SUCCESS = "SUCCESS"
TASK_FAILED = f"{ICON_DENY}FAILED"
TASK_SKIPPED = f"{ICON_WAIT}️SKIPPED"